name: Build Manuscript
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Environment
        run: source ci/install.sh
      - name: Build Manuscript
        run: bash build/build.sh
